In [2]:
import numpy as np
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans1-- Yes, there is a difference in the data type of variables list_ and array_list. list_ is a Python list object while array_list is a NumPy array object.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))      # Output: <class 'list'>
print(type(array_list)) # Output: <class 'numpy.ndarray'>


<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# print data type of each element in list_
for elem in list_:
    print(type(elem))

# print data type of each element in array_list
for elem in array_list:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Ans3-- Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list

Here, we are explicitly specifying the data type of the elements in array_list as int. This means that the elements in array_list will be converted from strings to integers.

To print the data types of each and every element present in both the variables list_ and array_list, you can use a loop to iterate over the elements and apply the type() function to each element. Here's how you can do it:

In [6]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# print data type of each element in list_
for elem in list_:
    print(type(elem))

# print data type of each element in array_list
for elem in array_list:
    print(type(elem))



<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

Ans4-- To find the shape and size of the NumPy array num_array defined in the question, you can use the shape and size attributes of the NumPy array. Here's how you can do it:

In [7]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [8]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# find shape of num_array
print("Shape of num_array:", num_array.shape)

# find size of num_array
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [9]:
import numpy as np

zero_array = np.zeros((3, 3))
print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [10]:
import numpy as np

identity_matrix = np.identity(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
